### ISSUE TITLE
Locations um Geo Informationen erweitern

### ISSUE THREAD

**Issue by benediktarnold** [mixandmatch/backend#2]
Der Location Service /locations soll im json Objekt auch die Geo Koordinaten zurück liefern. Helmut und Michael liefern dafür die Koordinaten. Diese sollen dann für die 4 Beispiellocations hardcoded eingebaut werden.

**Comment by michael-brueggemann** [comment]
HVU: http://www.openstreetmap.org/?mlat=48.188542&mlon=11.6474&zoom=18&layers=M
VGU: http://www.openstreetmap.org/?mlat=48.187483&mlon=11.647145&zoom=18&layers=M

**Comment by HelmutWiedemann** [comment]
Mace:
http://www.openstreetmap.org/?lat=48.18858&lon=11.654873&zoom=18&layers=M
http://maps.google.de/?q=48.18858+11.654873

Kistenpfennig: 
http://www.openstreetmap.org/?lat=48.168834&lon=11.586927&zoom=18&layers=M
http://maps.google.de/?q=48.168834+11.586927

**Comment by benediktarnold** [comment]
Ist deployt auf http://mixmatch-t.elasticbeanstalk.com/locations
